server:
  port: 8980
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.179.219:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.179.219:3306/yingxue?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 47.99.179.219
    port: 6379


mybatis:
  mapper-locations: classpath:com/timor/mapper/*.xml
  type-aliases-package: com.timor.entity
logging:
  level:
    com.timor.dao: debug
