server:
  port: 9999
spring:
  application:
    name: API-GATEWAY
  cloud:
    nacos:
      discovery:
        server-addr: 47.99.179.219:8848
    gateway:
      routes:
        #admins router
        - id: admins_router
          uri: lb://API-ADMINS
          predicates:
            - Path=/admin/tokens,/admin/admin-user,/admin/tokens/**
          filters:
            - StripPrefix=1
        #category router
        - id: category_router
          uri: lb://API-CATEGORY
          predicates:
            - Path=/admin/categories/**
          filters:
            - StripPrefix=1
        #user router
        - id: user_router
          uri: lb://API-USERS
          predicates:
            - Path=/user/demos
          filters:
            - StripPrefix=1
        #video router
        - id: video_router
          uri: lb://API-VIDEOS
          predicates:
            - Path=/video/demos
          filters:
            - StripPrefix=1

      globalcors: # 跨域配置处理
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"